CC = g++
default: Main
	./main
Main:  g++ main.cpp -o main.o
	./main	
Pt2ForLoop: g++ pt2forloop.cpp -o pt2forloop.o
		./pt2forloop
Pt2WhileLoop: g++ pt2whileloop.cpp -o pt2whileloop.o
		./pt2whileloop
